### PR TITLE
added support for aliased types.

### PR DESCRIPTION
**Pull request by wesdean**
This will allow the use of custom types that are aliased from already supported types.
I also added a "type" tag for those types that can't be effectively determined from an alias, such as time.Duration.

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Thanks for adding this support. I would have (incorrectly) assumed the reflection would have conveyed the resolved type at reflection time.

**Comment by itzg** [comment]
Well, I was just noticing that there isn't a build check wired into PRs and then noticed the build on master failed

https://app.circleci.com/pipelines/github/itzg/go-flagsfiller/12/workflows/d4d71e00-0448-4d49-8087-f9b02a66a28f/jobs/10?invite=true#step-105-4

(I'll work on getting github action based PR builds since that's what I'm no using elsewhere.)

**Comment by itzg** [comment]
...nm, it must have been a Go version thing since the Github Action with Go 1.17 tested fine:

https://github.com/itzg/go-flagsfiller/actions/runs/1665165297

**Comment by wesdean** [comment]
Yeah, I just checked. The Func function was added in 1.16 and your library uses 1.13.

I think this can be done differently if it needs to be. Would you rather me rework it or do you want to upgrade your Go version?

**Comment by itzg** [comment]
Thanks for investigating. I'm good with bumping the version in go.mod to 1.16.

**Pull request merged**
